//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceWCF
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientDto", Namespace="http://schemas.datacontract.org/2004/07/TradeCompanyApp.Domain.Models")]
    public partial class ClientDto : object
    {
        
        private System.DateTime CreatedAtField;
        
        private string DescriptionField;
        
        private string EmailField;
        
        private int IdField;
        
        private string NameField;
        
        private DataServiceWCF.OrderDto[] OrdersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataServiceWCF.OrderDto[] Orders
        {
            get
            {
                return this.OrdersField;
            }
            set
            {
                this.OrdersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDto", Namespace="http://schemas.datacontract.org/2004/07/TradeCompanyApp.Domain.Models")]
    public partial class OrderDto : object
    {
        
        private string AddressField;
        
        private DataServiceWCF.ClientDto ClientField;
        
        private int ClientIdField;
        
        private string DescriptionField;
        
        private int OrderIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataServiceWCF.ClientDto Client
        {
            get
            {
                return this.ClientField;
            }
            set
            {
                this.ClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId
        {
            get
            {
                return this.ClientIdField;
            }
            set
            {
                this.ClientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataServiceWCF.IDataService")]
    public interface IDataService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ClientExists", ReplyAction="http://tempuri.org/IDataService/ClientExistsResponse")]
        DataServiceWCF.ClientExistsResponse ClientExists(DataServiceWCF.ClientExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ClientExists", ReplyAction="http://tempuri.org/IDataService/ClientExistsResponse")]
        System.Threading.Tasks.Task<DataServiceWCF.ClientExistsResponse> ClientExistsAsync(DataServiceWCF.ClientExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ClientFind", ReplyAction="http://tempuri.org/IDataService/ClientFindResponse")]
        DataServiceWCF.ClientFindResponse ClientFind(DataServiceWCF.ClientFindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ClientFind", ReplyAction="http://tempuri.org/IDataService/ClientFindResponse")]
        System.Threading.Tasks.Task<DataServiceWCF.ClientFindResponse> ClientFindAsync(DataServiceWCF.ClientFindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ClientGet", ReplyAction="http://tempuri.org/IDataService/ClientGetResponse")]
        DataServiceWCF.ClientGetResponse ClientGet(DataServiceWCF.ClientGetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ClientGet", ReplyAction="http://tempuri.org/IDataService/ClientGetResponse")]
        System.Threading.Tasks.Task<DataServiceWCF.ClientGetResponse> ClientGetAsync(DataServiceWCF.ClientGetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ClientGetAll", ReplyAction="http://tempuri.org/IDataService/ClientGetAllResponse")]
        DataServiceWCF.ClientGetAllResponse ClientGetAll(DataServiceWCF.ClientGetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ClientGetAll", ReplyAction="http://tempuri.org/IDataService/ClientGetAllResponse")]
        System.Threading.Tasks.Task<DataServiceWCF.ClientGetAllResponse> ClientGetAllAsync(DataServiceWCF.ClientGetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ClientRemove", ReplyAction="http://tempuri.org/IDataService/ClientRemoveResponse")]
        DataServiceWCF.ClientRemoveResponse ClientRemove(DataServiceWCF.ClientRemoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ClientRemove", ReplyAction="http://tempuri.org/IDataService/ClientRemoveResponse")]
        System.Threading.Tasks.Task<DataServiceWCF.ClientRemoveResponse> ClientRemoveAsync(DataServiceWCF.ClientRemoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ClientCreate", ReplyAction="http://tempuri.org/IDataService/ClientCreateResponse")]
        DataServiceWCF.ClientCreateResponse ClientCreate(DataServiceWCF.ClientCreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ClientCreate", ReplyAction="http://tempuri.org/IDataService/ClientCreateResponse")]
        System.Threading.Tasks.Task<DataServiceWCF.ClientCreateResponse> ClientCreateAsync(DataServiceWCF.ClientCreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/OrderCreate", ReplyAction="http://tempuri.org/IDataService/OrderCreateResponse")]
        DataServiceWCF.OrderCreateResponse OrderCreate(DataServiceWCF.OrderCreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/OrderCreate", ReplyAction="http://tempuri.org/IDataService/OrderCreateResponse")]
        System.Threading.Tasks.Task<DataServiceWCF.OrderCreateResponse> OrderCreateAsync(DataServiceWCF.OrderCreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/OrderExists", ReplyAction="http://tempuri.org/IDataService/OrderExistsResponse")]
        DataServiceWCF.OrderExistsResponse OrderExists(DataServiceWCF.OrderExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/OrderExists", ReplyAction="http://tempuri.org/IDataService/OrderExistsResponse")]
        System.Threading.Tasks.Task<DataServiceWCF.OrderExistsResponse> OrderExistsAsync(DataServiceWCF.OrderExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/OrderFind", ReplyAction="http://tempuri.org/IDataService/OrderFindResponse")]
        DataServiceWCF.OrderFindResponse OrderFind(DataServiceWCF.OrderFindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/OrderFind", ReplyAction="http://tempuri.org/IDataService/OrderFindResponse")]
        System.Threading.Tasks.Task<DataServiceWCF.OrderFindResponse> OrderFindAsync(DataServiceWCF.OrderFindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/OrderGet", ReplyAction="http://tempuri.org/IDataService/OrderGetResponse")]
        DataServiceWCF.OrderGetResponse OrderGet(DataServiceWCF.OrderGetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/OrderGet", ReplyAction="http://tempuri.org/IDataService/OrderGetResponse")]
        System.Threading.Tasks.Task<DataServiceWCF.OrderGetResponse> OrderGetAsync(DataServiceWCF.OrderGetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/OrderGetAll", ReplyAction="http://tempuri.org/IDataService/OrderGetAllResponse")]
        DataServiceWCF.OrderGetAllResponse OrderGetAll(DataServiceWCF.OrderGetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/OrderGetAll", ReplyAction="http://tempuri.org/IDataService/OrderGetAllResponse")]
        System.Threading.Tasks.Task<DataServiceWCF.OrderGetAllResponse> OrderGetAllAsync(DataServiceWCF.OrderGetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/OrderRemove", ReplyAction="http://tempuri.org/IDataService/OrderRemoveResponse")]
        DataServiceWCF.OrderRemoveResponse OrderRemove(DataServiceWCF.OrderRemoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/OrderRemove", ReplyAction="http://tempuri.org/IDataService/OrderRemoveResponse")]
        System.Threading.Tasks.Task<DataServiceWCF.OrderRemoveResponse> OrderRemoveAsync(DataServiceWCF.OrderRemoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ClientUpdate", ReplyAction="http://tempuri.org/IDataService/ClientUpdateResponse")]
        DataServiceWCF.ClientUpdateResponse ClientUpdate(DataServiceWCF.ClientUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/ClientUpdate", ReplyAction="http://tempuri.org/IDataService/ClientUpdateResponse")]
        System.Threading.Tasks.Task<DataServiceWCF.ClientUpdateResponse> ClientUpdateAsync(DataServiceWCF.ClientUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/OrderUpdate", ReplyAction="http://tempuri.org/IDataService/OrderUpdateResponse")]
        DataServiceWCF.OrderUpdateResponse OrderUpdate(DataServiceWCF.OrderUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/OrderUpdate", ReplyAction="http://tempuri.org/IDataService/OrderUpdateResponse")]
        System.Threading.Tasks.Task<DataServiceWCF.OrderUpdateResponse> OrderUpdateAsync(DataServiceWCF.OrderUpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClientExists", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClientExistsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public ClientExistsRequest()
        {
        }
        
        public ClientExistsRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClientExistsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClientExistsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ClientExistsResult;
        
        public ClientExistsResponse()
        {
        }
        
        public ClientExistsResponse(bool ClientExistsResult)
        {
            this.ClientExistsResult = ClientExistsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClientFind", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClientFindRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<int> id;
        
        public ClientFindRequest()
        {
        }
        
        public ClientFindRequest(System.Nullable<int> id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClientFindResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClientFindResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DataServiceWCF.ClientDto ClientFindResult;
        
        public ClientFindResponse()
        {
        }
        
        public ClientFindResponse(DataServiceWCF.ClientDto ClientFindResult)
        {
            this.ClientFindResult = ClientFindResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClientGet", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClientGetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<int> id;
        
        public ClientGetRequest()
        {
        }
        
        public ClientGetRequest(System.Nullable<int> id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClientGetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClientGetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DataServiceWCF.ClientDto ClientGetResult;
        
        public ClientGetResponse()
        {
        }
        
        public ClientGetResponse(DataServiceWCF.ClientDto ClientGetResult)
        {
            this.ClientGetResult = ClientGetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClientGetAll", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClientGetAllRequest
    {
        
        public ClientGetAllRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClientGetAllResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClientGetAllResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DataServiceWCF.ClientDto[] ClientGetAllResult;
        
        public ClientGetAllResponse()
        {
        }
        
        public ClientGetAllResponse(DataServiceWCF.ClientDto[] ClientGetAllResult)
        {
            this.ClientGetAllResult = ClientGetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClientRemove", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClientRemoveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int clientDtoId;
        
        public ClientRemoveRequest()
        {
        }
        
        public ClientRemoveRequest(int clientDtoId)
        {
            this.clientDtoId = clientDtoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClientRemoveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClientRemoveResponse
    {
        
        public ClientRemoveResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClientCreate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClientCreateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DataServiceWCF.ClientDto clientDto;
        
        public ClientCreateRequest()
        {
        }
        
        public ClientCreateRequest(DataServiceWCF.ClientDto clientDto)
        {
            this.clientDto = clientDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClientCreateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClientCreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ClientCreateResult;
        
        public ClientCreateResponse()
        {
        }
        
        public ClientCreateResponse(int ClientCreateResult)
        {
            this.ClientCreateResult = ClientCreateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderCreate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OrderCreateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DataServiceWCF.OrderDto orderDto;
        
        public OrderCreateRequest()
        {
        }
        
        public OrderCreateRequest(DataServiceWCF.OrderDto orderDto)
        {
            this.orderDto = orderDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderCreateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OrderCreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int OrderCreateResult;
        
        public OrderCreateResponse()
        {
        }
        
        public OrderCreateResponse(int OrderCreateResult)
        {
            this.OrderCreateResult = OrderCreateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderExists", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OrderExistsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public OrderExistsRequest()
        {
        }
        
        public OrderExistsRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderExistsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OrderExistsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool OrderExistsResult;
        
        public OrderExistsResponse()
        {
        }
        
        public OrderExistsResponse(bool OrderExistsResult)
        {
            this.OrderExistsResult = OrderExistsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderFind", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OrderFindRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<int> id;
        
        public OrderFindRequest()
        {
        }
        
        public OrderFindRequest(System.Nullable<int> id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderFindResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OrderFindResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DataServiceWCF.OrderDto OrderFindResult;
        
        public OrderFindResponse()
        {
        }
        
        public OrderFindResponse(DataServiceWCF.OrderDto OrderFindResult)
        {
            this.OrderFindResult = OrderFindResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderGet", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OrderGetRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<int> id;
        
        public OrderGetRequest()
        {
        }
        
        public OrderGetRequest(System.Nullable<int> id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderGetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OrderGetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DataServiceWCF.OrderDto OrderGetResult;
        
        public OrderGetResponse()
        {
        }
        
        public OrderGetResponse(DataServiceWCF.OrderDto OrderGetResult)
        {
            this.OrderGetResult = OrderGetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderGetAll", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OrderGetAllRequest
    {
        
        public OrderGetAllRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderGetAllResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OrderGetAllResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DataServiceWCF.OrderDto[] OrderGetAllResult;
        
        public OrderGetAllResponse()
        {
        }
        
        public OrderGetAllResponse(DataServiceWCF.OrderDto[] OrderGetAllResult)
        {
            this.OrderGetAllResult = OrderGetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderRemove", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OrderRemoveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<int> orderId;
        
        public OrderRemoveRequest()
        {
        }
        
        public OrderRemoveRequest(System.Nullable<int> orderId)
        {
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderRemoveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OrderRemoveResponse
    {
        
        public OrderRemoveResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClientUpdate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClientUpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DataServiceWCF.ClientDto clientDto;
        
        public ClientUpdateRequest()
        {
        }
        
        public ClientUpdateRequest(DataServiceWCF.ClientDto clientDto)
        {
            this.clientDto = clientDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClientUpdateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClientUpdateResponse
    {
        
        public ClientUpdateResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderUpdate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OrderUpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DataServiceWCF.OrderDto orderDto;
        
        public OrderUpdateRequest()
        {
        }
        
        public OrderUpdateRequest(DataServiceWCF.OrderDto orderDto)
        {
            this.orderDto = orderDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderUpdateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OrderUpdateResponse
    {
        
        public OrderUpdateResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IDataServiceChannel : DataServiceWCF.IDataService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<DataServiceWCF.IDataService>, DataServiceWCF.IDataService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DataServiceClient() : 
                base(DataServiceClient.GetDefaultBinding(), DataServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IDataService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(DataServiceClient.GetBindingForEndpoint(endpointConfiguration), DataServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DataServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DataServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public DataServiceWCF.ClientExistsResponse ClientExists(DataServiceWCF.ClientExistsRequest request)
        {
            return base.Channel.ClientExists(request);
        }
        
        public System.Threading.Tasks.Task<DataServiceWCF.ClientExistsResponse> ClientExistsAsync(DataServiceWCF.ClientExistsRequest request)
        {
            return base.Channel.ClientExistsAsync(request);
        }
        
        public DataServiceWCF.ClientFindResponse ClientFind(DataServiceWCF.ClientFindRequest request)
        {
            return base.Channel.ClientFind(request);
        }
        
        public System.Threading.Tasks.Task<DataServiceWCF.ClientFindResponse> ClientFindAsync(DataServiceWCF.ClientFindRequest request)
        {
            return base.Channel.ClientFindAsync(request);
        }
        
        public DataServiceWCF.ClientGetResponse ClientGet(DataServiceWCF.ClientGetRequest request)
        {
            return base.Channel.ClientGet(request);
        }
        
        public System.Threading.Tasks.Task<DataServiceWCF.ClientGetResponse> ClientGetAsync(DataServiceWCF.ClientGetRequest request)
        {
            return base.Channel.ClientGetAsync(request);
        }
        
        public DataServiceWCF.ClientGetAllResponse ClientGetAll(DataServiceWCF.ClientGetAllRequest request)
        {
            return base.Channel.ClientGetAll(request);
        }
        
        public System.Threading.Tasks.Task<DataServiceWCF.ClientGetAllResponse> ClientGetAllAsync(DataServiceWCF.ClientGetAllRequest request)
        {
            return base.Channel.ClientGetAllAsync(request);
        }
        
        public DataServiceWCF.ClientRemoveResponse ClientRemove(DataServiceWCF.ClientRemoveRequest request)
        {
            return base.Channel.ClientRemove(request);
        }
        
        public System.Threading.Tasks.Task<DataServiceWCF.ClientRemoveResponse> ClientRemoveAsync(DataServiceWCF.ClientRemoveRequest request)
        {
            return base.Channel.ClientRemoveAsync(request);
        }
        
        public DataServiceWCF.ClientCreateResponse ClientCreate(DataServiceWCF.ClientCreateRequest request)
        {
            return base.Channel.ClientCreate(request);
        }
        
        public System.Threading.Tasks.Task<DataServiceWCF.ClientCreateResponse> ClientCreateAsync(DataServiceWCF.ClientCreateRequest request)
        {
            return base.Channel.ClientCreateAsync(request);
        }
        
        public DataServiceWCF.OrderCreateResponse OrderCreate(DataServiceWCF.OrderCreateRequest request)
        {
            return base.Channel.OrderCreate(request);
        }
        
        public System.Threading.Tasks.Task<DataServiceWCF.OrderCreateResponse> OrderCreateAsync(DataServiceWCF.OrderCreateRequest request)
        {
            return base.Channel.OrderCreateAsync(request);
        }
        
        public DataServiceWCF.OrderExistsResponse OrderExists(DataServiceWCF.OrderExistsRequest request)
        {
            return base.Channel.OrderExists(request);
        }
        
        public System.Threading.Tasks.Task<DataServiceWCF.OrderExistsResponse> OrderExistsAsync(DataServiceWCF.OrderExistsRequest request)
        {
            return base.Channel.OrderExistsAsync(request);
        }
        
        public DataServiceWCF.OrderFindResponse OrderFind(DataServiceWCF.OrderFindRequest request)
        {
            return base.Channel.OrderFind(request);
        }
        
        public System.Threading.Tasks.Task<DataServiceWCF.OrderFindResponse> OrderFindAsync(DataServiceWCF.OrderFindRequest request)
        {
            return base.Channel.OrderFindAsync(request);
        }
        
        public DataServiceWCF.OrderGetResponse OrderGet(DataServiceWCF.OrderGetRequest request)
        {
            return base.Channel.OrderGet(request);
        }
        
        public System.Threading.Tasks.Task<DataServiceWCF.OrderGetResponse> OrderGetAsync(DataServiceWCF.OrderGetRequest request)
        {
            return base.Channel.OrderGetAsync(request);
        }
        
        public DataServiceWCF.OrderGetAllResponse OrderGetAll(DataServiceWCF.OrderGetAllRequest request)
        {
            return base.Channel.OrderGetAll(request);
        }
        
        public System.Threading.Tasks.Task<DataServiceWCF.OrderGetAllResponse> OrderGetAllAsync(DataServiceWCF.OrderGetAllRequest request)
        {
            return base.Channel.OrderGetAllAsync(request);
        }
        
        public DataServiceWCF.OrderRemoveResponse OrderRemove(DataServiceWCF.OrderRemoveRequest request)
        {
            return base.Channel.OrderRemove(request);
        }
        
        public System.Threading.Tasks.Task<DataServiceWCF.OrderRemoveResponse> OrderRemoveAsync(DataServiceWCF.OrderRemoveRequest request)
        {
            return base.Channel.OrderRemoveAsync(request);
        }
        
        public DataServiceWCF.ClientUpdateResponse ClientUpdate(DataServiceWCF.ClientUpdateRequest request)
        {
            return base.Channel.ClientUpdate(request);
        }
        
        public System.Threading.Tasks.Task<DataServiceWCF.ClientUpdateResponse> ClientUpdateAsync(DataServiceWCF.ClientUpdateRequest request)
        {
            return base.Channel.ClientUpdateAsync(request);
        }
        
        public DataServiceWCF.OrderUpdateResponse OrderUpdate(DataServiceWCF.OrderUpdateRequest request)
        {
            return base.Channel.OrderUpdate(request);
        }
        
        public System.Threading.Tasks.Task<DataServiceWCF.OrderUpdateResponse> OrderUpdateAsync(DataServiceWCF.OrderUpdateRequest request)
        {
            return base.Channel.OrderUpdateAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDataService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDataService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64642/DataServiceWCF.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DataServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IDataService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DataServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IDataService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IDataService,
        }
    }
}
